'use client';
import { useEffect, useState } from 'react';
import RotatingContainer from '@/components/yard/RotatingContainer';
import { Container, Plus, Search, ArrowUpRight, RefreshCw, MapPin, PackageCheck, Clock3, Grid2X2, ArrowRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Toaster, toast } from 'sonner';
type Item={id:string;code:string;owner:string;size:string;cargo:string;position:string|null;status:string;created:string;updated:string;version:number};
const positions=['A','B','C'].flatMap(s=>Array.from({length:12},(_,i)=>`${s}-${String(i+1).padStart(2,'0')}`));
const statusNames:Record<string,string>={waiting:'Aguardando',allocated:'Alocado',departed:'Saída registrada'};
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full bg-white"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [data,setData]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[selected,setSelected]=useState<Item|null>(null),[position,setPosition]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({code:'',owner:'',size:'20',cargo:''});
 async function load(){setLoading(true);try{const r=await fetch('/api/containers');const d=await r.json() as Item[] & {error?:string};if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'start_container_registration',description:'Abre o formulário para cadastrar um contêiner; não salva registros.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Informe um objeto vazio.');setOpen(true);return {form:'registration',open:true}}},{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}return()=>lifecycle.abort()},[]);
 async function save(method:string,payload:unknown){setBusy(true);try{const r=await fetch('/api/containers',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();setOpen(false);setSelected(null);setForm({code:'',owner:'',size:'20',cargo:''});toast.success('Registro salvo com sucesso.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const occupied=data.filter(x=>x.status==='allocated'),waiting=data.filter(x=>x.status==='waiting'),departed=data.filter(x=>x.status==='departed');
 const visible=data.filter(x=>(filter==='all'||x.status===filter)&&`${x.code} ${x.owner} ${x.position??''}`.toLowerCase().includes(query.toLowerCase()));
 const pick=(item:Item)=>{setSelected(item);setPosition(item.position??'')};
 return <><Toaster richColors position="top-right"/><header className="topbar"><a href="/" className="brand"><span className="brandmark"><Container size={24}/></span>PÁTIO<span className="brand-sub">GESTÃO DE CONTÊINERES</span></a><div className="workspace"><span className="workspace-icon">P</span>Meu terminal<span className="private">Privado</span></div></header>
 <main className="shell"><div className="eyebrow">OPERAÇÃO / VISÃO GERAL</div><div className="heading"><div><h1>Controle do pátio</h1><p>Do recebimento à saída, cada contêiner em seu lugar.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Novo contêiner</button></div>
 <div className="stats">{[{title:'Contêineres no pátio',n:occupied.length,sub:'Posições ocupadas',icon:Container},{title:'Posições disponíveis',n:36-occupied.length,sub:'De 36 posições no total',icon:Grid2X2},{title:'Aguardando alocação',n:waiting.length,sub:'Prontos para posicionar',icon:Clock3},{title:'Ocupação do pátio',n:`${Math.round(occupied.length/36*100)}%`,sub:'Capacidade utilizada',icon:PackageCheck}].map((s,i)=><div className={`stat stat-${i}`} key={s.title}><div className="stat-label">{s.title}<s.icon size={19}/></div><strong>{loading?'—':s.n}</strong><span>{s.sub}</span>{i===3&&<div className="meter"><i style={{width:`${occupied.length/36*100}%`}}/></div>}</div>)}</div>
 {error&&<div className="error" role="alert">{error}<button onClick={load}>Tentar novamente</button></div>}
 <div className="operation"><section className="yard panel"><div className="panel-head"><div className="title-icon"><MapPin size={20}/><h2>Mapa do pátio</h2></div><button className="icon-button" onClick={load} aria-label="Atualizar pátio" disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/></button></div><div className="map-meta"><span>3 setores · 12 posições por setor</span><div className="legend"><span><i className="free-key"/>Livre</span><span><i className="occupied-key"/>Ocupada</span></div></div><div className="yard-map">{['A','B','C'].map(sector=><div className="sector" key={sector}><div className="sector-head"><strong>SETOR {sector}</strong><span>{occupied.filter(x=>x.position?.startsWith(sector)).length}/12 ocupadas</span></div><div className="slots">{positions.filter(p=>p.startsWith(sector)).map(p=>{const c=occupied.find(x=>x.position===p);return <button disabled={loading||!!error} key={p} className={`slot ${c?'taken':''}`} title={c?`${p} · ${c.code}`:`${p} · Livre`} onClick={()=>{if(c)pick(c);else{setPosition(p);setSelected({id:'choose'} as Item)}}}><span>{p}</span>{c?<><Container size={19}/><small>{c.code.slice(-7)}</small></>:<><Plus size={17}/><small>Livre</small></>}</button>})}</div></div>)}</div><div className="map-footer"><span>Via de circulação</span><ArrowRight size={18}/></div><p className="map-note">Posições de até 40 pés · 1 contêiner por posição · Sem empilhamento</p></section>
 <aside className="queue panel"><RotatingContainer/><div className="panel-head"><h2>Fila de alocação</h2><span className="count">{waiting.length}</span></div><p className="queue-intro">Contêineres aguardando uma posição.</p>{loading?<p className="empty-text">Carregando registros…</p>:waiting.length?waiting.slice(0,5).map(c=><button className="queue-item" key={c.id} onClick={()=>pick(c)}><span className="queue-symbol"><Container size={21}/></span><span><b>{c.code}</b><small>{c.owner} · {c.size} pés</small></span><ArrowUpRight size={17}/></button>):<div className="queue-empty"><PackageCheck size={36}/><h3>Tudo em seu lugar</h3><p>Novos contêineres aparecem aqui até serem alocados.</p><button className="text-button" onClick={()=>setOpen(true)}>Cadastrar contêiner <Plus size={15}/></button></div>}<div className="queue-bottom"><span>Saídas registradas</span><strong>{departed.length}</strong></div></aside></div>
 <section className="records panel"><div className="records-heading"><div><h2>Contêineres</h2><p>Consulte os registros e gerencie as movimentações.</p></div><div className="search"><Search size={18}/><input aria-label="Buscar contêiner ou cliente" placeholder="Buscar código, cliente ou posição" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">Todos ({data.length})</TabsTrigger><TabsTrigger value="allocated">Alocados</TabsTrigger><TabsTrigger value="waiting">Aguardando</TabsTrigger><TabsTrigger value="departed">Saídas</TabsTrigger></TabsList><TabsContent value={filter}><Table><TableHeader><TableRow>{['CONTÊINER','CLIENTE / CARGA','TAMANHO','POSIÇÃO','STATUS',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(c=><TableRow key={c.id}><TableCell><b className="code">{c.code}</b><small className="date">Entrada em {new Date(c.created).toLocaleDateString('pt-BR')}</small></TableCell><TableCell>{c.owner}<small className="date">{c.cargo||'Carga não informada'}</small></TableCell><TableCell>{c.size} pés</TableCell><TableCell><span className="position-label">{c.position||'—'}</span></TableCell><TableCell><span className={`badge ${c.status}`}>{statusNames[c.status]}</span></TableCell><TableCell><button className="text-button" onClick={()=>pick(c)}>{c.status==='departed'?'Detalhes':'Gerenciar'}<ArrowUpRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<div className="table-empty"><Container size={28}/><h3>{loading?'Carregando contêineres…':data.length?'Nenhum resultado encontrado':'Seu pátio está pronto para começar'}</h3><p>{data.length?'Experimente outro termo ou filtro.':'Cadastre o primeiro contêiner e escolha uma posição no mapa.'}</p></div>}</TabsContent></Tabs><footer className="table-footer">{visible.length} de {data.length} registros</footer></section><footer className="footer"><span>PÁTIO <span> / Controle de alocação</span></span><span>Organização em cada movimento.</span></footer></main>
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="modal"><DialogTitle>Novo contêiner</DialogTitle><DialogDescription>Após o cadastro, selecione uma posição para alocar.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save('POST',form)}}><label>Código do contêiner<input required pattern="[A-Z]{4}[0-9]{7}" maxLength={11} placeholder="ABCU1234567" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/><small>4 letras e 7 números.</small></label><label>Cliente / responsável<input required maxLength={100} placeholder="Nome do cliente" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>Tamanho<Choice label="Tamanho" value={form.size} onChange={size=>setForm({...form,size})} items={['20','40'].map(value=>({value,label:`${value} pés`}))}/></label><label>Carga (opcional)<input maxLength={200} placeholder="Descrição da carga" value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})}/></label><button disabled={busy} className="primary full" type="submit">{busy?'Salvando…':'Cadastrar contêiner'}</button></form></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>!v&&!busy&&setSelected(null)}><DialogContent className="modal"><DialogTitle>{selected?.id==='choose'?`Alocar na posição ${position}`:selected?.code}</DialogTitle><DialogDescription>{selected?.id==='choose'?'Selecione um contêiner da fila.':`${selected?.owner??''} · ${selected?.size??''} pés`}</DialogDescription>{selected?.id==='choose'?<div>{waiting.length?waiting.map(c=><button key={c.id} className="pick-row" disabled={busy} onClick={()=>save('PATCH',{id:c.id,version:c.version,action:'allocate',position})}>{c.code}<ArrowRight size={17}/></button>):<p className="empty-text">Não há contêineres aguardando. Cadastre um contêiner primeiro.</p>}</div>:selected&&<><div className="detail"><span className={`badge ${selected.status}`}>{statusNames[selected.status]}</span><p>Carga: {selected.cargo||'Não informada'}</p><p>Posição atual: <b>{selected.position||'Não alocado'}</b></p><p>Última atualização: {new Date(selected.updated).toLocaleString('pt-BR')}</p></div>{selected.status!=='departed'&&<><label>Posição de destino<Choice label="Selecione uma posição livre" value={position} onChange={setPosition} items={positions.filter(p=>!occupied.some(c=>c.position===p&&c.id!==selected.id)).map(value=>({value,label:value}))}/></label><button className="primary full" disabled={busy||!position||position===selected.position} onClick={()=>save('PATCH',{id:selected.id,version:selected.version,action:'allocate',position})}>{busy?'Salvando…':selected.position?'Mover contêiner':'Confirmar alocação'}</button>{selected.position&&<button className="secondary full" disabled={busy} onClick={()=>save('PATCH',{id:selected.id,version:selected.version,action:'release'})}>Liberar posição e voltar à fila</button>}<button className="departure" disabled={busy} onClick={()=>save('PATCH',{id:selected.id,version:selected.version,action:'depart'})}>Registrar saída do pátio <ArrowUpRight size={16}/></button><small className="muted">A saída libera a posição e mantém o registro para consulta.</small></>}</>}</DialogContent></Dialog>
 </>;
}
